
GET http://localhost:3000/movies/

###1

POST http://localhost:3000/movies/
Content-Type:application/json

{
  "directorId": 6,
  "movieName": "Jurassic Park",
  "leadActor": "Jeff Goldblum"
}

###2

GET http://localhost:3000/movies/7/

###3
PUT http://localhost:3000/movies/1/
Content-Type : application/json

{
  "directorId": 24,
  "movieName": "Thor",
  "leadActor": "Christopher Hemsworth"
}

###4
DELETE http://localhost:3000/movies/1/

###5
GET http://localhost:3000/directors/

###6
GET http://localhost:3000/directors/3/movies/

###7